title: <p align="center"> Bao Chu </p>
description: 
  <br>   
  I just graduated Bachelor in Agriculture Economics, and now I am
  pursuing masters in Data Science through Upgrad, the journey has been
  awesome, looking forward to meeting new people and exploring new paths 
  ahead
  <br>
  </p>
  
theme: jekyll-theme-hacker
